eureka:
  client:
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:8300/eureka
  instance:
    hostname: localhost
server:
  port: 8302
spring:
  application:
    name: order_service