eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8300/eureka
    enabled: true
  instance:
      hostname: localhost
server:
  port: 8303
spring:
  application:
    name: db_service
