eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8300/eureka
  instance:
      hostname: localhost
server:
  port: 8304
spring:
  application:
    name: db_service
